image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: healthcare

stages:
  - build
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker compose -f docker-compose.yaml build
    - docker images

deploy:
  stage: deploy
  only:
    - main
  before_script:
    # Tạo thư mục SSH và thêm private key từ biến môi trường
    - mkdir -p ~/.ssh
    - echo "$AWS_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # Cấu hình SSH để không kiểm tra host key
    - echo -e "Host $AWS_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script:
    # Tạo thư mục `app` trên EC2
    - ssh -i ~/.ssh/id_rsa $AWS_USER@$AWS_HOST "mkdir -p ~/app"
    # Copy file `docker-compose.yaml` lên EC2
    - scp -i ~/.ssh/id_rsa docker-compose.yaml $AWS_USER@$AWS_HOST:~/app/
    # Triển khai ứng dụng bằng Docker Compose
    - ssh -i ~/.ssh/id_rsa $AWS_USER@$AWS_HOST "
        cd ~/app &&
        docker compose down &&
        docker compose up -d --build
      "
  environment:
    name: production
    url: http://$AWS_HOST
