image: docker:27.3.1

services:
  - docker:27.3.1-dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: healthcare

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Build stage
build:
  stage: build
  script:
    - docker compose -f docker-compose.yaml build
    - docker images



# Deploy stage (only for main branch)
deploy:
  stage: deploy
  only:
    - main
  script:
    - docker compose -f docker-compose.yaml up -d --build
    - echo "Deployed successfully on main branch"
  environment:
    name: production
    url: http://localhost
