version: '3.8'
services:
  database-mysql:
    container_name: database-mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=hoidanit
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    command: --lower_case_table_names=1
    expose:
      - 3306
    volumes:
      - ./hoidanit.sql:/docker-entrypoint-initdb.d/hoidanit.sql
      - ./studentdb.sql:/docker-entrypoint-initdb.d/studentdb.sql
      - ./udpmailserver.sql:/docker-entrypoint-initdb.d/udpmailserver.sql

  backend:
    container_name: backend
    build:
      context: ./Healcare-NodeJS-Server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      - URL_REACT=http://localhost
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    container_name: nginx
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ./Healcare-client-ReactJS/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

